### ISSUE TITLE
browser.rb key spliting error

### ISSUE THREAD

**Issue by zeboudja** [humante/redis-browser#19]
Hello, I’ve the following exception :

- ArgumentError - invalid byte sequence in UTF-8:
        /usr/lib/ruby/gems/2.2.0/gems/redis-browser-0.3.2/lib/redis-browser/browser.rb:8:in `split_key'
        /usr/lib/ruby/gems/2.2.0/gems/redis-browser-0.3.2/lib/redis-browser/browser.rb:26:in `block in keys'

**Comment by nicpillinger** [comment]
+1
