### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by esquinas** [humante/redis-browser#43]

**Comment by szajbus** [comment]
It seems I don't have much time to properly maintain it. I would happily welcome a co-maintainer.

**Comment by esquinas** [comment]
Hello Michał, I don't have lots of spare time either, but I would like to help. I code in Ruby for my daily job, on remote.

**Comment by szajbus** [comment]
Enrique, I just gave you write access to the repository (sent an invite). Hopefully you can take care of some issues and PRs in your spare time :)
