### ISSUE TITLE
Subresource Integrity

### ISSUE THREAD

**Issue by kaloyanm** [humante/redis-browser#47]
When accessing the _Redis browser_, a script is loaded from an external URL. The integrity of this
script cannot be verified. It is caused by the following line inside [index.slim](https://github.com/humante/redis-browser/blob/master/lib/redis-browser/templates/index.slim):

```html
script type="text/javascript" src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"
```
This is known as [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity). Since protecting the website delivery is important to our line of work, we are ready to provide PR for resolving this issue.

Thank you for your understanding! :bow:

**Comment by szajbus** [comment]
Perfect, thanks!
